web: update chokidar
By running `npm update chokidar`, this resolves various issues during
`npm start` for web:

    Error: No version of chokidar is available. Tried chokidar@2 and chokidar@3.
    You could try to manually install any chokidar version.
    chokidar@3: Error: Cannot find module 'chokidar'
    Require stack:
    - /home/user/WebProjects/cbr-platform/web/node_modules/watchpack/lib/chokidar.js
    - /home/user/WebProjects/cbr-platform/web/node_modules/watchpack/lib/DirectoryWatcher.js
    - /home/user/WebProjects/cbr-platform/web/node_modules/watchpack/lib/watcherManager.js
    - /home/user/WebProjects/cbr-platform/web/node_modules/watchpack/lib/watchpack.js
    - /home/user/WebProjects/cbr-platform/web/node_modules/webpack/lib/node/NodeWatchFileSystem.js
    - /home/user/WebProjects/cbr-platform/web/node_modules/webpack/lib/node/NodeEnvironmentPlugin.js
    - /home/user/WebProjects/cbr-platform/web/node_modules/webpack/lib/webpack.js
    - /home/user/WebProjects/cbr-platform/web/node_modules/react-scripts/scripts/start.js
    chokidar@2: Error: Cannot find module 'watchpack-chokidar2'
    Require stack:
    - /home/user/WebProjects/cbr-platform/web/node_modules/watchpack/lib/chokidar.js
    - /home/user/WebProjects/cbr-platform/web/node_modules/watchpack/lib/DirectoryWatcher.js
    - /home/user/WebProjects/cbr-platform/web/node_modules/watchpack/lib/watcherManager.js
    - /home/user/WebProjects/cbr-platform/web/node_modules/watchpack/lib/watchpack.js
    - /home/user/WebProjects/cbr-platform/web/node_modules/webpack/lib/node/NodeWatchFileSystem.js
    - /home/user/WebProjects/cbr-platform/web/node_modules/webpack/lib/node/NodeEnvironmentPlugin.js
    - /home/user/WebProjects/cbr-platform/web/node_modules/webpack/lib/webpack.js
    - /home/user/WebProjects/cbr-platform/web/node_modules/react-scripts/scripts/start.js